improve prepush script

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -54,7 +54,7 @@ if [[ $(uname -m) != 'aarch64' ]]; then
  (mkdir -p .build.icpx           && cd .build.icpx           && CXX=/opt/intel/oneapi/compiler/latest/bin/icpx                cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23                                                                                                                                  && cmake --build . $CMT && ctest --parallel --output-on-failure $CTR) || exit 666
  (mkdir -p .build.nvc++          && cd .build.nvc++          && CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/2024/compilers/bin/nvc++ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-stdpar=multicore" -DBLA_PREFER_PKGCONFIG=ON-DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2024/compilers/bin/nvc++            && cmake --build . $CMT && ctest --parallel --output-on-failure $CTR) || exit 666
  (mkdir -p .build.culang         && cd .build.culang         &&                                                               cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=clang++ -DCMAKE_CUDA_HOST_COMPILER=clang++ -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CUDA_ARCHITECTURES=75              && cmake --build . $CMT && ctest --parallel --output-on-failure $CTR) || exit 666
- (mkdir -p .build.clang++.mull   && cd .build.clang++.mull   && CXX=clang++-16                                                cmake .. -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_FLAGS="-O0 -fpass-plugin=/usr/lib/mull-ir-frontend-16 -g -grecord-command-line -fprofile-instr-generate -fcoverage-mapping"                  && cmake --build . $CMT && (ls test/*.x | xargs -n 1 sh -c 'echo $0 && ((mull-runner-16 $0 --ld-search-path /usr/lib --test-program=ctest -- -j2 --stop-on-failure) || exit 255)') ) || exit 666
+#(mkdir -p .build.clang++.mull   && cd .build.clang++.mull   && CXX=clang++-16                                                cmake .. -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_FLAGS="-O0 -fpass-plugin=/usr/lib/mull-ir-frontend-16 -g -grecord-command-line -fprofile-instr-generate -fcoverage-mapping"                  && cmake --build . $CMT && (ls test/*.x | xargs -n 1 sh -c 'echo $0 && ((mull-runner-16 $0 --ld-search-path /usr/lib --test-program=ctest -- -j2 --stop-on-failure) || exit 255)') ) || exit 666
 fi
 
 # find ./detail/ -name "*.hpp" \( -exec iwyu -std=c++17 -Xiwyu --mapping_file=/usr/share/include-what-you-use/stl.c.headers.imp -Xiwyu --mapping_file=$HOME/boost-multi/.iwyu-test.imp  -Xiwyu --error=0 -Xiwyu --max_line_length=200 -Xiwyu --quoted_includes_first -Xiwyu --cxx17ns {} -I$HOME/boost-multi/include/ \; -o -quit \)
@@ -71,7 +71,6 @@ else
 # ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"
 #(mkdir -p .build.g++-14    && cd .build.g++-14    && CXX=g++-14                                cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=23                                                          && cmake --build . $CMT &&                                           ctest -j 12 --output-on-failure $CTR) || exit 666
  (mkdir -p .build.c++.std23 && cd .build.c++.std23 && CXX=c++ CXXFLAGS="-fexperimental-library" cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23                     && cmake --build . $CMT &&                                           (ctest --parallel $CTR || ctest --rerun-failed --output-on-failure $CTR) ) || exit 666
-#(mkdir -p .build.mull      && cd .build.mull      && CXX=c++ CXXFLAGS="-O1 -fpass-plugin=~/bin/mull-ir-frontend-16 -g -grecord-command-line -fprofile-instr-generate -fcoverage-mapping" cmake ..                  && cmake --build . $CMT &&                                           (ls *.x | xargs -n 1 sh -c 'echo $0 && ((~/bin/mull-runner-16 $0 -test-program=ctest -- -j2 --stop-on-failure) || exit 255)')) || exit 666
  (mkdir -p .build.c++.asan  && cd .build.c++.asan  && CXX=c++                                   cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-D_LIBCPP_DEBUG=1 -fsanitize=undefined -fsanitize=pointer-overflow -fsanitize-trap=pointer-overflow -fsanitize=address -fno-omit-frame-pointer -fsanitize=signed-integer-overflow" && cmake --build . $CMT && ASAN_OPTIONS="new_delete_type_mismatch=1" ctest -j 12 --output-on-failure $CTR) || exit 666
  (mkdir -p .build.c++.m32   && cd .build.c++.m32   && CXX=c++                                   cmake .. -DCMAKE_BUILD_TYPE=Debug                                                                                  && cmake --build . $CMT &&                                           ctest -j 12 --output-on-failure $CTR) || exit 666
  (mkdir -p .build.c++.tidy  && cd .build.c++.tidy  && CXX=c++                                   cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_CLANG_TIDY=clang-tidy -DCMAKE_CXX_CPPLINT="cpplint;--quiet" -DCMAKE_CXX_CPPCHECK="cppcheck;--enable=all;--suppress=missingIncludeSystem;--checkers-report=cppcheck.report;--suppress=checkersReport;--inline-suppr;--std=c++17;--error-exitcode=1" -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;--mapping_file=/Users/correatedesco1/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls;-Xiwyu;--error" && cmake --build . $CMT --verbose --parallel && ctest -j 12 --output-on-failure $CTR) || exit 666
