awkward fine-grained control over excess memory capacity

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -2,7 +2,7 @@
 # sudo apt install git cmake ninja-build ccache g++ clang clang-20 binutils-gold libboost-dev make libclang-rt-dev libc++-dev nvidia-cuda-toolkit libfftw3-dev valgrind clang-tidy --no-install-recommends
 # sudo apt install git cmake ninja-build ccache g++ clang binutils-gold libboost-dev make libclang-rt-dev libc++-dev nvidia-cuda-toolkit pkg-config libfftw3-dev valgrind clang-tidy --no-install-recommends
 # sudo dnf install boost-devel blas-devel ccache clang clang-tools-extra cmake cppcheck fftw-devel git lcov libasan liblas-devel libubsan ninja-build valgrind
-# install circle # mkdir -p $HOME/bin && wget https://www.circle-lang.org/linux/circle_linux_x86_64.tgz -P $HOME/tmp/ && tar zxvf $HOME/tmp/circle_linux_x86_64.tgz --directory $HOME/bin/ && $HOME/bin/circle --version
+# install circle # mkdir -p $HOME/bin && wget https://www.circle-lang.org/download/circle_linux_x86_64.tgz -P $HOME/tmp/ && tar zxvf $HOME/tmp/circle_linux_x86_64.tgz --directory $HOME/bin/ && $HOME/bin/circle --version
 # install nvc++
 #   on Ubuntu:
 #     curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
@@ -69,6 +69,8 @@ PATH="/usr/bin:$PATH" asciidoctor-pdf --safe-mode unsafe --failure-level WARN -a
 
 if [[ $(uname -m) != 'aarch64' ]]; then
 (clang-format-21 --version 2>/dev/null && clang-format-21 --output-replacements-xml --dry-run -Werror include/**/*.hpp test/*.cpp || exit 666) || echo "clang-format-21 not installed"
+
+ (DIR=.build.circle;         [ -d "$DIR" ] || CXX="$HOME/bin/circle"                     cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Debug                                                                                                       -DCMAKE_CXX_STANDARD=20 -DDISABLE_MPI=1 -DCMAKE_CXX_EXTENSIONS=OFF -DENABLE_CIRCLE=1 -DCMAKE_THREAD_LIBS_INIT="-lpthread" -DCMAKE_CXX_COMPILER_LAUNCHER=                                                                                                                                                                                                                                                                     && cmake --build "$DIR" $CMT                      &&                                           ctest --test-dir "$DIR"                                                                                                                                                                                                                                                                               $CTR ) || echo "$HOME/bin/circle not installed or build failed"
 
  (DIR=.build.nvcc.debug;     [ -d "$DIR" ] ||                                           cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Debug          -DCMAKE_COMPILE_WARNING_AS_ERROR=ON                                                          -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--extended-lambda --threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++-12 -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_CUDA_ARCHITECTURES=native                                                                                                                                                                                                                                                           && cmake --build "$DIR" $CMT                      &&                                           ctest --test-dir "$DIR"                                                                                                                                                                                                                                                                               $CTR )
  (DIR=.build.nvc++26;        [ -d "$DIR" ] ||                                           cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Release        -DCMAKE_COMPILE_WARNING_AS_ERROR=ON                                                          -DCMAKE_CXX_STANDARD=20 -DBLA_PREFER_PKGCONFIG=ON -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2026/compilers/bin/nvc++                                                                                                                                                                                                                                                                                                                                                && cmake --build "$DIR" $CMT                      &&                                           ctest --test-dir "$DIR"                                                                                                                                                                                                                                                                               $CTR )
