fix ub

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -35,17 +35,17 @@ if [[ $(uname -m) != 'arm64' ]]; then
 
 export VALGRIND_EXE="valgrind --trace-children=yes --leak-check=full --track-origins=yes --show-leak-kinds=all --suppressions=.valgrind_suppressions --gen-suppressions=all --error-exitcode=1 "
 export PMIX_MCA_gds=hash
-
+export UBSAN_OPTIONS=print_stacktrack=1
 
  (mkdir -p .build.clang++        && cd .build.clang++        && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Debug                                                                                                                                                            && cmake --build . $CMT &&  (ctest --parallel 2 $CTR || ctest --rerun-failed --output-on-failure $CTR) ) || exit 666
  (mkdir -p .build.clang++-rel    && cd .build.clang++-rel    && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Release                                                                                                                                                          && cmake --build . $CMT &&  (ctest --parallel 2 $CTR || ctest --rerun-failed --output-on-failure $CTR) ) || exit 666
  (mkdir -p .build.g++            && cd .build.g++            && CXX=g++                                                       cmake .. -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_EXPORT_COMPILE_COMMANDS=ON                                                                                                                       && cmake --build . $CMT &&  (ctest --parallel 2 $CTR || ctest --rerun-failed --output-on-failure $CTR) ) || exit 666
+ (mkdir -p .build.clang++.plus   && cd .build.clang++.plus   && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DBLA_VENDOR=Generic `#-DCMAKE_CXX_CLANG_TIDY="clang-tidy"` -DCMAKE_CXX_FLAGS="-g -fsanitize=undefined -fno-sanitize-recover=undefined -DUBSAN=1" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=undefined" `#-DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="iwyu;-Xiwyu;--mapping_file=/home/correaa/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls"` && cmake --build . $CMT && (ctest --parallel $CTR || ctest --parallel 1 --output-on-failure $CTR)) || exit 666
  (mkdir -p .build.clang++        && cd .build.clang++        && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Debug                                                                                                                                                            && cmake --build . $CMT &&  ctest --parallel 2 --output-on-failure $CTR) || exit 666
  (mkdir -p .build.clang++.libcpp && cd .build.clang++.libcpp && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-stdlib=libc++"                                                                                               && cmake --build . $CMT &&  ctest --parallel 2 --output-on-failure $CTR) || exit 666
  (mkdir -p .build.g++-rel        && cd .build.g++-rel        && CXX=g++                                                       cmake .. -DCMAKE_BUILD_TYPE=Release                                                                                                                                                          && cmake --build . $CMT &&  ctest --parallel 2 --output-on-failure $CTR) || exit 666
 #(mkdir -p .build.g++.m32        && cd .build.g++.m32        && CXX=g++ CXXFLAGS="-m32"                                       cmake .. -DCMAKE_BUILD_TYPE=Debug                                                                                                                                                            && cmake --build . && ctest --parallel 2 --output-on-failure) || exit 666
  (mkdir -p .build.g++.plus       && cd .build.g++.plus       && CXX=g++                                                       cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23 -DBLA_VENDOR=OpenBLAS `#-DCMAKE_CXX_CPPCHECK="cppcheck;--enable=all;--suppress=missingIncludeSystem;--inline-suppr;--std=c++17;--checkers-report=cppcheck.report;--error-exitcode=1"` -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG=1" -DCMAKE_CXX_FLAGS="-fconcepts-diagnostics-depth=4 -fimplicit-constexpr -fanalyzer -Wno-analyzer-null-dereference -Wno-analyzer-possible-null-dereference -Wno-analyzer-malloc-leak -Wno-analyzer-use-of-uninitialized-value -Wno-analyzer-use-after-free" && cmake --build . $CMT && (PMIX_MCA_gds=hash ctest --parallel 8 -T memcheck $CTR || PMIX_MCA_gds=hash ctest --verbose --rerun-failed --output-on-failure -T memcheck $CTR) ) || exit 666
- (mkdir -p .build.clang++.plus   && cd .build.clang++.plus   && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DBLA_VENDOR=Generic -DCMAKE_CXX_CLANG_TIDY="clang-tidy" `#-DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="iwyu;-Xiwyu;--mapping_file=/home/correaa/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls"` && cmake --build . $CMT && ASAN_OPTIONS="new_delete_type_mismatch=0" ctest --parallel --output-on-failure $CTR) || exit 666
 #(mkdir -p .build.hip            && cd .build.hip            && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_HIP_COMPILER=/opt/rocm/llvm/bin/clang++ -DCMAKE_CXX_FLAGS="-DMULTI_USE_HIP" -DCMAKE_HIP_FLAGS="-DMULTI_USE_HIP" -DENABLE_HIP=1 -DCMAKE_HIP_ARCHITECTURES=gfx90a && cmake --build . )                           || exit 666
 #(mkdir -p .build.g++-.cov       && cd .build.g++-.cov       && CXX=g++                                                       cmake .. -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_FLAGS="--coverage -lgcov -fno-inline -fno-inline-small-functions -fno-default-inline" -DCMAKE_EXE_LINKER_FLAGS="-lgcov --coverage"           && cmake --build . && ASAN_OPTIONS="new_delete_type_mismatch=0" ctest -j 12 --output-on-failure -T Test `# && lcov --directory . --capture --output-file coverage.info && lcov --remove coverage.info '/usr/*' --output-file coverage.info && lcov --list coverage.info && genhtml coverage.info`) || exit 666
 
