tblis

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -40,15 +40,15 @@ if [[ $OSTYPE != "darwin"* ]]; then
 export PMIX_MCA_gds=hash
 export UBSAN_OPTIONS=print_stacktrack=1
 
- (CXX=g++                           cmake -S . -B .build.g++            -DCMAKE_BUILD_TYPE=Debug                                                              && cmake --build .build.g++            $CMT && (ctest --test-dir .build.g++            $CTR || ctest --test-dir .build.g++            --rerun-failed --output-on-failure $CTR) ) || exit 666
- (CXX=clang++                       cmake -S . -B .build.clang++-rel    -DCMAKE_BUILD_TYPE=Release                                                            && cmake --build .build.clang++-rel    $CMT && (ctest --test-dir .build.clang++-rel    $CTR || ctest --test-dir .build.clang++-rel    --rerun-failed --output-on-failure $CTR) ) || exit 666
- (CXX=clang++-16                    cmake -S . -B .build.clang++-16     -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20                                    && cmake --build .build.clang++-16     $CMT && (ctest --test-dir .build.clang++-16     $CTR || ctest --test-dir .build.clang++-16     --rerun-failed --output-on-failure $CTR) ) || exit 666
- (CXX=clang++ CXXFLAGS=-Weverything cmake -S . -B .build.clang++        -DCMAKE_BUILD_TYPE=Debug                                                              && cmake --build .build.clang++        $CMT && (ctest --test-dir .build.clang++        $CTR || ctest --test-dir .build.clang++        --rerun-failed --output-on-failure $CTR) ) || exit 666
- (CXX=clang++                       cmake -S . -B .build.clang++.c++23  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23                                    && cmake --build .build.clang++.c++23  $CMT && (ctest --test-dir .build.clang++.c++23  $CTR || ctest --test-dir .build.clang++.c++23  --rerun-failed --output-on-failure $CTR) ) || exit 666
- (CXX=g++                           cmake -S . -B .build.g++.c++23      -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=23                                    && cmake --build .build.g++.c++23      $CMT && (ctest --test-dir .build.g++.c++23      $CTR || ctest --test-dir .build.g++.c++23      --rerun-failed --output-on-failure $CTR) ) || exit 666
- (CXX=clang++                       cmake -S . -B .build.clang++        -DCMAKE_BUILD_TYPE=Debug                                                              && cmake --build .build.clang++        $CMT && (ctest --test-dir .build.clang++        $CTR || ctest --test-dir .build.clang++        --rerun-failed --output-on-failure $CTR) ) || exit 666
- (CXX=clang++                       cmake -S . -B .build.clang++.libcpp -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=23 -DCMAKE_CXX_FLAGS="-stdlib=libc++" && cmake --build .build.clang++.libcpp $CMT && (ctest --test-dir .build.clang++.libcpp $CTR || ctest --test-dir .build.clang++.libcpp --rerun-failed --output-on-failure $CTR) ) || exit 666
- (CXX=g++                           cmake -S . -B .build.g++-rel        -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE                  && cmake --build .build.g++-rel        $CMT && (ctest --test-dir .build.g++-rel        $CTR || ctest --test-dir .build.g++-rel        --rerun-failed --output-on-failure $CTR) ) || exit 666
+ (CXX=g++                           cmake -S . -B .build.g++            -DCMAKE_BUILD_TYPE=Debug                                                               && cmake --build .build.g++            $CMT && (ctest --test-dir .build.g++            $CTR || ctest --test-dir .build.g++            --rerun-failed --output-on-failure $CTR) ) || exit 666
+ (CXX=clang++                       cmake -S . -B .build.clang++-rel    -DCMAKE_BUILD_TYPE=Release -DENABLE_TBLIS=ON                                           && cmake --build .build.clang++-rel    $CMT && (ctest --test-dir .build.clang++-rel    $CTR || ctest --test-dir .build.clang++-rel    --rerun-failed --output-on-failure $CTR) ) || exit 666
+ (CXX=clang++-16                    cmake -S . -B .build.clang++-16     -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20                                     && cmake --build .build.clang++-16     $CMT && (ctest --test-dir .build.clang++-16     $CTR || ctest --test-dir .build.clang++-16     --rerun-failed --output-on-failure $CTR) ) || exit 666
+ (CXX=clang++ CXXFLAGS=-Weverything cmake -S . -B .build.clang++        -DCMAKE_BUILD_TYPE=Debug                                                               && cmake --build .build.clang++        $CMT && (ctest --test-dir .build.clang++        $CTR || ctest --test-dir .build.clang++        --rerun-failed --output-on-failure $CTR) ) || exit 666
+ (CXX=clang++                       cmake -S . -B .build.clang++.c++23  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23                                     && cmake --build .build.clang++.c++23  $CMT && (ctest --test-dir .build.clang++.c++23  $CTR || ctest --test-dir .build.clang++.c++23  --rerun-failed --output-on-failure $CTR) ) || exit 666
+ (CXX=g++                           cmake -S . -B .build.g++.c++23      -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=23                                     && cmake --build .build.g++.c++23      $CMT && (ctest --test-dir .build.g++.c++23      $CTR || ctest --test-dir .build.g++.c++23      --rerun-failed --output-on-failure $CTR) ) || exit 666
+ (CXX=clang++                       cmake -S . -B .build.clang++        -DCMAKE_BUILD_TYPE=Debug                                                               && cmake --build .build.clang++        $CMT && (ctest --test-dir .build.clang++        $CTR || ctest --test-dir .build.clang++        --rerun-failed --output-on-failure $CTR) ) || exit 666
+ (CXX=clang++                       cmake -S . -B .build.clang++.libcpp -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=23 -DCMAKE_CXX_FLAGS="-stdlib=libc++"  && cmake --build .build.clang++.libcpp $CMT && (ctest --test-dir .build.clang++.libcpp $CTR || ctest --test-dir .build.clang++.libcpp --rerun-failed --output-on-failure $CTR) ) || exit 666
+ (CXX=g++                           cmake -S . -B .build.g++-rel        -DCMAKE_BUILD_TYPE=Release -DENABLE_TBLIS=ON -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE && cmake --build .build.g++-rel        $CMT && (ctest --test-dir .build.g++-rel        $CTR || ctest --test-dir .build.g++-rel        --rerun-failed --output-on-failure $CTR) ) || exit 666
 
 if [[ $(uname -m) != 'aarch64' ]]; then
  clang-format-19 --output-replacements-xml --dry-run -Werror include/**/*.hpp test/*.cpp
@@ -75,9 +75,9 @@ else
 # git clone thrust; cd thrust; mkdir build; cd build; cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME -DTHRUST_ENABLE_HEADER_TESTING=OFF -DTHRUST_ENABLE_TESTING=OFF -DTHRUST_ENABLE_EXAMPLES=OFF
 export CMAKE_PREFIX_PATH=$HOME/lib/cmake/thrust
 #export Thurst_DIR=/Users/correatedesco1/include/thrust/cmake
- (CXX=c++ CXXFLAGS="-fexperimental-library" cmake -S . -B .build.c++.std23 -DCMAKE_BUILD_TYPE=Debug   `#-DOpenMP_ROOT=/opt/homebrew/opt/libomp` -DCMAKE_CXX_STANDARD=23                                                                                                                                                                                                       && cmake --build .build.c++.std23 $CMT &&                                           (ctest --test-dir .build.c++.std23 $CTR                      || ctest --verbose --test-dir .build.c++.std23 --rerun-failed --output-on-failure $CTR) ) || exit 666
- (CXX=c++                                   cmake -S . -B .build.c++.asan  -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-D_LIBCPP_DEBUG=1 -fsanitize=undefined -fsanitize=pointer-overflow -fsanitize-trap=pointer-overflow -fsanitize=address -fno-omit-frame-pointer -fsanitize=signed-integer-overflow" && cmake --build .build.c++.asan  $CMT && ASAN_OPTIONS="new_delete_type_mismatch=1"  ctest --test-dir .build.c++.asan  $CTR --output-on-failure                                                                                          ) || exit 666
- (CXX=g++-15                                cmake -S . -B .build.g++-15    -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DDISABLE_TBLIS=ON -DCMAKE_CXX_STANDARD=23 -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE -DCMAKE_CXX_FLAGS="-D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG=1 -D_FORTIFY_SOURCE=3"                                                                            && cmake --build .build.g++-15    $CMT &&                                            ctest --test-dir .build.g++-15    $CTR --output-on-failure                                                                                          ) || exit 666
+ (CXX=c++ CXXFLAGS="-fexperimental-library" cmake -S . -B .build.c++.std23 -DCMAKE_BUILD_TYPE=Debug   `#-DOpenMP_ROOT=/opt/homebrew/opt/libomp` -DENABLE_TBLIS=ON -DCMAKE_CXX_STANDARD=23                                                                                                                                                                                                       && cmake --build .build.c++.std23 $CMT &&                                           (ctest --test-dir .build.c++.std23 $CTR                      || ctest --verbose --test-dir .build.c++.std23 --rerun-failed --output-on-failure $CTR) ) || exit 666
+ (CXX=c++                                   cmake -S . -B .build.c++.asan  -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DENABLE_TBLIS=ON -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-D_LIBCPP_DEBUG=1 -fsanitize=undefined -fsanitize=pointer-overflow -fsanitize-trap=pointer-overflow -fsanitize=address -fno-omit-frame-pointer -fsanitize=signed-integer-overflow" && cmake --build .build.c++.asan  $CMT && ASAN_OPTIONS="new_delete_type_mismatch=1"  ctest --test-dir .build.c++.asan  $CTR --output-on-failure                                                                                          ) || exit 666
+ (CXX=g++-15                                cmake -S . -B .build.g++-15    -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DCMAKE_CXX_STANDARD=23 -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE -DCMAKE_CXX_FLAGS="-D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG=1 -D_FORTIFY_SOURCE=3"                                                                            && cmake --build .build.g++-15    $CMT &&                                            ctest --test-dir .build.g++-15    $CTR --output-on-failure                                                                                          ) || exit 666
  (CXX=c++                                   cmake -S . -B .build.c++.plus  -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    `#-DCMAKE_CXX_CLANG_TIDY=clang-tidy` -DCMAKE_CXX_CPPLINT="cpplint;--quiet" -DDISABLE_TBLIS=ON -DCMAKE_CXX_FLAGS="-DCPPCHECK=1" -DCMAKE_CXX_CPPCHECK="cppcheck;-DCPPCHECK=1;--enable=all;--suppress=preprocessorErrorDirective;--suppress=missingIncludeSystem;--suppress=unhandledChar;--checkers-report=cppcheck.report;--suppress=checkersReport;--suppress=syntaxError;--suppress=unmatchedSuppression;--suppress=unusedFunction;--suppress=constParameterReference;--suppress=normalCheckLevelMaxBranches;--inline-suppr;--std=c++17;--error-exitcode=1" -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;--mapping_file=/Users/correatedesco1/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls;-Xiwyu;-Werror" && cmake --build .build.c++.plus $CMT --verbose --parallel && (ctest --test-dir .build.c++.plus -j 12 $CTR || ctest --test-dir .build.c++.tidy --rerun-failed --output-on-failure $CTR)) || exit 666
 
 if [[ $(uname -m) == 'arm64' ]]; then
