lwyu

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -63,7 +63,7 @@ if [[ $(uname -m) != 'aarch64' ]]; then
 (clang-format-21 --version 2>/dev/null && clang-format-21 --output-replacements-xml --dry-run -Werror include/**/*.hpp test/*.cpp || exit 666) || echo "clang-format-21 not installed" 
 #diff -u include/**/*.hpp test/*.cpp <(clang-format-19 include/**/*.hpp test/*.cpp)
 
-(CXX="$HOME/bin/circle" cmake -S . -B .build.circle     -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DDISABLE_MPI=1 -DCMAKE_CXX_EXTENSIONS=OFF -DENABLE_CIRCLE=1 -DCMAKE_THREAD_LIBS_INIT="-lpthread"                                                                                              && cmake --build .build.circle     $CMT && (ctest --test-dir .build.circle     $CTR || ctest --test-dir .build.circle     --rerun-failed $CTR)) || exit 666
+(CXX="$HOME/bin/circle" cmake -S . -B .build.circle     -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DDISABLE_MPI=1 -DCMAKE_CXX_EXTENSIONS=OFF -DENABLE_CIRCLE=1 -DCMAKE_THREAD_LIBS_INIT="-lpthread" -DCMAKE_CXX_COMPILER_LAUNCHER=                                                                     && cmake --build .build.circle     $CMT && (ctest --test-dir .build.circle     $CTR || ctest --test-dir .build.circle     --rerun-failed $CTR)) || exit 666
 #nice -n 15 bash -c '(DIR=.build.nvcc.debug-cu17; [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=17 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--extended-lambda --threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++-12 -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvcc.debug-cu17 $CMT && (ctest --test-dir .build.nvcc.debug-cu17 $CTR || ctest --test-dir .build.nvcc.debug-cu17 --rerun-failed $CTR))' || exit 666
  nice -n 15 bash -c '(DIR=.build.nvcc.debug;      [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--extended-lambda --threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++-12 -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvcc.debug      $CMT && (ctest --test-dir .build.nvcc.debug $CTR      || ctest --test-dir .build.nvcc.debug      --rerun-failed $CTR))' || exit 666
 #nice -n 15 bash -c '(DIR=.build.nvc++.nvcc13.debug;    [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2026/compilers/bin/nvcc -DCMAKE_CUDA_FLAGS="--extended-lambda --threads 2" -DCMAKE_CUDA_HOST_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2026/compilers/bin/nvc++ -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2026/compilers/bin/nvc++ -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvc++.nvcc13.debug    $CMT && (ctest --test-dir .build.nvc++.nvcc13.debug $CTR    || ctest --test-dir .build.nvc++.nvcc13.debug    --rerun-failed $CTR))' || exit 666
@@ -99,7 +99,7 @@ export CMAKE_PREFIX_PATH=$HOME/lib/cmake/thrust
  (CXX=c++ CXXFLAGS="-fexperimental-library" cmake -S . -B .build.c++.std23 -DCMAKE_BUILD_TYPE=Debug -DENABLE_TBLIS=ON -DCMAKE_CXX_STANDARD=23                                                                                                                                                                                                       && cmake --build .build.c++.std23 $CMT &&                                           (ctest --test-dir .build.c++.std23 $CTR                      || ctest --verbose --test-dir .build.c++.std23 --rerun-failed $CTR) ) || exit 666
  (CXX=c++                                   cmake -S . -B .build.c++.asan  -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DENABLE_TBLIS=ON -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-D_LIBCPP_DEBUG=1 -fsanitize=undefined -fsanitize=pointer-overflow -fsanitize-trap=pointer-overflow -fsanitize=address -fno-omit-frame-pointer -fsanitize=signed-integer-overflow" && cmake --build .build.c++.asan  $CMT && ASAN_OPTIONS="new_delete_type_mismatch=1"  ctest --test-dir .build.c++.asan  $CTR                                                                                          ) || exit 666
  (CXX=g++-14                                cmake -S . -B .build.g++-14    -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DCMAKE_CXX_STANDARD=23 -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE -DCMAKE_CXX_FLAGS="-D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG=1 -D_FORTIFY_SOURCE=3"                                                                            && cmake --build .build.g++-14    $CMT &&                                            ctest --test-dir .build.g++-14    $CTR                                                                                          ) || exit 666
- (CXX=c++                                   cmake -S . -B .build.c++.plus  -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOpenMP_ROOT=/opt/homebrew/opt/libomp    `#-DCMAKE_CXX_CLANG_TIDY=clang-tidy` -DCMAKE_CXX_CPPLINT="cpplint;--quiet" -DCMAKE_CXX_FLAGS="-DCPPCHECK=1 -Werror=deprecated-declarations" -DCMAKE_CXX_CPPCHECK="cppcheck;-DCPPCHECK=1;--enable=all;--suppress=preprocessorErrorDirective;--suppress=missingIncludeSystem;--suppress=unhandledChar;--checkers-report=cppcheck.report;--suppress=checkersReport;--suppress=syntaxError;--suppress=unmatchedSuppression;--suppress=unusedFunction;--suppress=constParameterReference;--suppress=normalCheckLevelMaxBranches;--inline-suppr;--std=c++17;--error-exitcode=1" -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;--mapping_file=/Users/correatedesco1/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls;-Xiwyu;-Werror" && cmake --build .build.c++.plus $CMT --verbose --parallel && (ctest --test-dir .build.c++.plus $CTR || ctest --test-dir .build.c++.tidy --rerun-failed $CTR)) || exit 666
+ (CXX=c++                                   cmake -S . -B .build.c++.plus  -DCMAKE_BUILD_TYPE=RelWithDebInfo -DOpenMP_ROOT=/opt/homebrew/opt/libomp    `#-DCMAKE_CXX_CLANG_TIDY=clang-tidy` -DCMAKE_CXX_CPPLINT="cpplint;--quiet" -DCMAKE_CXX_FLAGS="-DCPPCHECK=1 -Werror=deprecated-declarations" -DCMAKE_CXX_CPPCHECK="cppcheck;-DCPPCHECK=1;--enable=all;--suppress=preprocessorErrorDirective;--suppress=missingIncludeSystem;--suppress=unhandledChar;--checkers-report=cppcheck.report;--suppress=checkersReport;--suppress=syntaxError;--suppress=unmatchedSuppression;--suppress=unusedFunction;--suppress=constParameterReference;--suppress=normalCheckLevelMaxBranches;--inline-suppr;--std=c++17;--error-exitcode=1" -DCMAKE_LINK_WHAT_YOU_USE=ON -DCMAKE_LINK_WHAT_YOU_USE=ON -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;--mapping_file=/Users/correatedesco1/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls;-Xiwyu;-Werror" && cmake --build .build.c++.plus $CMT --verbose --parallel && (ctest --test-dir .build.c++.plus $CTR || ctest --test-dir .build.c++.tidy --rerun-failed $CTR)) || exit 666
  (CXX=clang++                               cmake -S . -B .build.c++.std26 -DCMAKE_BUILD_TYPE=Release                                                                                                                        -DCMAKE_CXX_STANDARD=26                                                                                                                                                                                                       && cmake --build .build.c++.std26 $CMT &&                                           (ctest --test-dir .build.c++.std26 $CTR                      || ctest --verbose --test-dir .build.c++.std26 --rerun-failed $CTR) ) || exit 666
 
 if [[ $(uname -m) == 'arm64' ]]; then
