fix viewable_range concept

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -38,12 +38,12 @@ export PMIX_MCA_gds=hash
 
 
  (mkdir -p .build.clang++-rel    && cd .build.clang++-rel    && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Release                                                                                                                                                          && cmake --build . $CMT &&  (ctest --parallel 2 $CTR || ctest --rerun-failed --output-on-failure $CTR) ) || exit 666
- (mkdir -p .build.g++            && cd .build.g++            && CXX=g++                                                       cmake .. -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_EXPORT_COMPILE_COMMANDS=ON                                                                                                                       && cmake --build . $CMT &&  ctest --parallel 2 --output-on-failure $CTR) || exit 666
+ (mkdir -p .build.g++            && cd .build.g++            && CXX=g++                                                       cmake .. -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_EXPORT_COMPILE_COMMANDS=ON                                                                                                                       && cmake --build . $CMT &&  (ctest --parallel 2 $CTR || ctest --rerun-failed --output-on-failure $CTR) ) || exit 666
  (mkdir -p .build.clang++        && cd .build.clang++        && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Debug                                                                                                                                                            && cmake --build . $CMT &&  ctest --parallel 2 --output-on-failure $CTR) || exit 666
- (mkdir -p .build.clang++.libcpp && cd .build.clang++.libcpp && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_CXX_STANDARD=20  -DCMAKE_CXX_FLAGS="-stdlib=libc++"                                                                                               && cmake --build . $CMT &&  ctest --parallel 2 --output-on-failure $CTR) || exit 666
+ (mkdir -p .build.clang++.libcpp && cd .build.clang++.libcpp && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-stdlib=libc++"                                                                                               && cmake --build . $CMT &&  ctest --parallel 2 --output-on-failure $CTR) || exit 666
  (mkdir -p .build.g++-rel        && cd .build.g++-rel        && CXX=g++                                                       cmake .. -DCMAKE_BUILD_TYPE=Release                                                                                                                                                          && cmake --build . $CMT &&  ctest --parallel 2 --output-on-failure $CTR) || exit 666
 #(mkdir -p .build.g++.m32        && cd .build.g++.m32        && CXX=g++ CXXFLAGS="-m32"                                       cmake .. -DCMAKE_BUILD_TYPE=Debug                                                                                                                                                            && cmake --build . && ctest --parallel 2 --output-on-failure) || exit 666
- (mkdir -p .build.g++.plus       && cd .build.g++.plus       && CXX=g++                                                       cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23 -DBLA_VENDOR=OpenBLAS `#-DCMAKE_CXX_CPPCHECK="cppcheck;--enable=all;--suppress=missingIncludeSystem;--inline-suppr;--std=c++17;--checkers-report=cppcheck.report;--error-exitcode=1"` -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG=1" -DCMAKE_CXX_FLAGS="-fimplicit-constexpr -fanalyzer -Wno-analyzer-null-dereference -Wno-analyzer-possible-null-dereference -Wno-analyzer-malloc-leak -Wno-analyzer-use-of-uninitialized-value -Wno-analyzer-use-after-free" && cmake --build . $CMT && (PMIX_MCA_gds=hash ctest --parallel 8 -T memcheck $CTR || PMIX_MCA_gds=hash ctest --verbose --rerun-failed --output-on-failure -T memcheck $CTR) ) || exit 666
+ (mkdir -p .build.g++.plus       && cd .build.g++.plus       && CXX=g++                                                       cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23 -DBLA_VENDOR=OpenBLAS `#-DCMAKE_CXX_CPPCHECK="cppcheck;--enable=all;--suppress=missingIncludeSystem;--inline-suppr;--std=c++17;--checkers-report=cppcheck.report;--error-exitcode=1"` -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG=1" -DCMAKE_CXX_FLAGS="-fconcepts-diagnostics-depth=4 -fimplicit-constexpr -fanalyzer -Wno-analyzer-null-dereference -Wno-analyzer-possible-null-dereference -Wno-analyzer-malloc-leak -Wno-analyzer-use-of-uninitialized-value -Wno-analyzer-use-after-free" && cmake --build . $CMT && (PMIX_MCA_gds=hash ctest --parallel 8 -T memcheck $CTR || PMIX_MCA_gds=hash ctest --verbose --rerun-failed --output-on-failure -T memcheck $CTR) ) || exit 666
  (mkdir -p .build.clang++.plus   && cd .build.clang++.plus   && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DBLA_VENDOR=Generic -DCMAKE_CXX_CLANG_TIDY="clang-tidy" `#-DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="iwyu;-Xiwyu;--mapping_file=/home/correaa/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls"` && cmake --build . $CMT && ASAN_OPTIONS="new_delete_type_mismatch=0" ctest --parallel --output-on-failure $CTR) || exit 666
 #(mkdir -p .build.hip            && cd .build.hip            && CXX=clang++                                                   cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_HIP_COMPILER=/opt/rocm/llvm/bin/clang++ -DCMAKE_CXX_FLAGS="-DMULTI_USE_HIP" -DCMAKE_HIP_FLAGS="-DMULTI_USE_HIP" -DENABLE_HIP=1 -DCMAKE_HIP_ARCHITECTURES=gfx90a && cmake --build . )                           || exit 666
 #(mkdir -p .build.g++-.cov       && cd .build.g++-.cov       && CXX=g++                                                       cmake .. -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_FLAGS="--coverage -lgcov -fno-inline -fno-inline-small-functions -fno-default-inline" -DCMAKE_EXE_LINKER_FLAGS="-lgcov --coverage"           && cmake --build . && ASAN_OPTIONS="new_delete_type_mismatch=0" ctest -j 12 --output-on-failure -T Test `# && lcov --directory . --capture --output-file coverage.info && lcov --remove coverage.info '/usr/*' --output-file coverage.info && lcov --list coverage.info && genhtml coverage.info`) || exit 666
@@ -51,7 +51,7 @@ export PMIX_MCA_gds=hash
 if [[ $(uname -m) != 'aarch64' ]]; then
  (mkdir -p .build.circle         && cd .build.circle         && CXX="$HOME/bin/circle"                                        cmake .. -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DDISABLE_MPI=1 -DCMAKE_CXX_EXTENSIONS=OFF -DENABLE_CIRCLE=1 -DCMAKE_THREAD_LIBS_INIT="-lpthread"                                && cmake --build . $CMT && (ctest --parallel $CTR || ctest --rerun-failed --output-on-failure $CTR)) || exit 666
  (mkdir -p .build.nvcc           && cd .build.nvcc           &&                                                               cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=75 && cmake --build . $CMT && ctest --parallel --output-on-failure $CTR) || exit 666
- (mkdir -p .build.icpx           && cd .build.icpx           && CXX=/opt/intel/oneapi/compiler/latest/bin/icpx                cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23                                                                                                                                  && cmake --build . $CMT && ctest --parallel --output-on-failure $CTR) || exit 666
+ (mkdir -p .build.icpx           && cd .build.icpx           && CXX=/opt/intel/oneapi/compiler/latest/bin/icpx                cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20                                                                                                                                  && cmake --build . $CMT && ctest --parallel --output-on-failure $CTR) || exit 666
  (mkdir -p .build.nvc++          && cd .build.nvc++          && CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/2024/compilers/bin/nvc++ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-stdpar=multicore" -DBLA_PREFER_PKGCONFIG=ON-DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2024/compilers/bin/nvc++            && cmake --build . $CMT && ctest --parallel --output-on-failure $CTR) || exit 666
  (mkdir -p .build.culang         && cd .build.culang         &&                                                               cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=clang++ -DCMAKE_CUDA_HOST_COMPILER=clang++ -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CUDA_ARCHITECTURES=75              && cmake --build . $CMT && ctest --parallel --output-on-failure $CTR) || exit 666
 #(mkdir -p .build.clang++.mull   && cd .build.clang++.mull   && CXX=clang++-16                                                cmake .. -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_FLAGS="-O0 -fpass-plugin=/usr/lib/mull-ir-frontend-16 -g -grecord-command-line -fprofile-instr-generate -fcoverage-mapping"                  && cmake --build . $CMT && (ls test/*.x | xargs -n 1 sh -c 'echo $0 && ((mull-runner-16 $0 --ld-search-path /usr/lib --test-program=ctest -- -j2 --stop-on-failure) || exit 255)') ) || exit 666
