debug info

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -77,12 +77,12 @@ export CMAKE_PREFIX_PATH=$HOME/lib/cmake/thrust
 #export Thurst_DIR=/Users/correatedesco1/include/thrust/cmake
  (CXX=c++ CXXFLAGS="-fexperimental-library" cmake -S . -B .build.c++.std23 -DCMAKE_BUILD_TYPE=Debug   `#-DOpenMP_ROOT=/opt/homebrew/opt/libomp` -DCMAKE_CXX_STANDARD=23                                                                                                                                                                                                       && cmake --build .build.c++.std23 $CMT &&                                           (ctest --test-dir .build.c++.std23 $CTR                      || ctest --verbose --test-dir .build.c++.std23 --rerun-failed --output-on-failure $CTR) ) || exit 666
  (CXX=c++                                   cmake -S . -B .build.c++.asan  -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-D_LIBCPP_DEBUG=1 -fsanitize=undefined -fsanitize=pointer-overflow -fsanitize-trap=pointer-overflow -fsanitize=address -fno-omit-frame-pointer -fsanitize=signed-integer-overflow" && cmake --build .build.c++.asan  $CMT && ASAN_OPTIONS="new_delete_type_mismatch=1"  ctest --test-dir .build.c++.asan  $CTR --output-on-failure                                                                                          ) || exit 666
- (CXX=g++-15                                cmake -S . -B .build.g++-15    -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DDISABLE_TBLIS=1 -DCMAKE_CXX_STANDARD=23 -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE -DCMAKE_CXX_FLAGS="-D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG=1 -D_FORTIFY_SOURCE=3"                                                                            && cmake --build .build.g++-15    $CMT &&                                            ctest --test-dir .build.g++-15    $CTR --output-on-failure                                                                                          ) || exit 666
- (CXX=c++                                   cmake -S . -B .build.c++.plus  -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    `#-DCMAKE_CXX_CLANG_TIDY=clang-tidy` -DCMAKE_CXX_CPPLINT="cpplint;--quiet" -DDISABLE_TBLIS=1 -DCMAKE_CXX_FLAGS="-DCPPCHECK=1" -DCMAKE_CXX_CPPCHECK="cppcheck;-DCPPCHECK=1;--enable=all;--suppress=preprocessorErrorDirective;--suppress=missingIncludeSystem;--suppress=unhandledChar;--checkers-report=cppcheck.report;--suppress=checkersReport;--suppress=syntaxError;--suppress=unmatchedSuppression;--suppress=unusedFunction;--suppress=constParameterReference;--suppress=normalCheckLevelMaxBranches;--inline-suppr;--std=c++17;--error-exitcode=1" -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;--mapping_file=/Users/correatedesco1/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls;-Xiwyu;-Werror" && cmake --build .build.c++.plus $CMT --verbose --parallel && (ctest --test-dir .build.c++.plus -j 12 $CTR || ctest --test-dir .build.c++.tidy --rerun-failed --output-on-failure $CTR)) || exit 666
+ (CXX=g++-15                                cmake -S . -B .build.g++-15    -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DDISABLE_TBLIS=ON -DCMAKE_CXX_STANDARD=23 -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE -DCMAKE_CXX_FLAGS="-D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG=1 -D_FORTIFY_SOURCE=3"                                                                            && cmake --build .build.g++-15    $CMT &&                                            ctest --test-dir .build.g++-15    $CTR --output-on-failure                                                                                          ) || exit 666
+ (CXX=c++                                   cmake -S . -B .build.c++.plus  -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    `#-DCMAKE_CXX_CLANG_TIDY=clang-tidy` -DCMAKE_CXX_CPPLINT="cpplint;--quiet" -DDISABLE_TBLIS=ON -DCMAKE_CXX_FLAGS="-DCPPCHECK=1" -DCMAKE_CXX_CPPCHECK="cppcheck;-DCPPCHECK=1;--enable=all;--suppress=preprocessorErrorDirective;--suppress=missingIncludeSystem;--suppress=unhandledChar;--checkers-report=cppcheck.report;--suppress=checkersReport;--suppress=syntaxError;--suppress=unmatchedSuppression;--suppress=unusedFunction;--suppress=constParameterReference;--suppress=normalCheckLevelMaxBranches;--inline-suppr;--std=c++17;--error-exitcode=1" -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;--mapping_file=/Users/correatedesco1/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls;-Xiwyu;-Werror" && cmake --build .build.c++.plus $CMT --verbose --parallel && (ctest --test-dir .build.c++.plus -j 12 $CTR || ctest --test-dir .build.c++.tidy --rerun-failed --output-on-failure $CTR)) || exit 666
 
 if [[ $(uname -m) == 'arm64' ]]; then
- (CXX=c++                                   cmake -S . -B .build.c++.m32   -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DCMAKE_CXX_FLAGS="-m32" -DDISABLE_TBLIS=1                                                                                                                                                                                                      && cmake --build .build.c++.m32   $CMT &&                                            ctest --test-dir .build.c++.m32   $CTR --output-on-failure                                                                                          ) || exit 666
- (CXX=c++                                   cmake -S . -B .build.c++.tidy  -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DDISABLE_TBLIS=1 -DCMAKE_CXX_CLANG_TIDY=clang-tidy                                                                                                                                                                                             && cmake --build .build.c++.tidy  $CMT &&                                            ctest --test-dir .build.c++.tidy  $CTR --output-on-failure                                                                                          ) || exit 666
+ (CXX=c++                                   cmake -S . -B .build.c++.m32   -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DCMAKE_CXX_FLAGS="-m32" -DDISABLE_TBLIS=ON                                                                                                                                                                                                      && cmake --build .build.c++.m32   $CMT &&                                            ctest --test-dir .build.c++.m32   $CTR --output-on-failure                                                                                          ) || exit 666
+ (CXX=c++                                   cmake -S . -B .build.c++.tidy  -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DDISABLE_TBLIS=ON -DCMAKE_CXX_CLANG_TIDY=clang-tidy                                                                                                                                                                                             && cmake --build .build.c++.tidy  $CMT &&                                            ctest --test-dir .build.c++.tidy  $CTR --output-on-failure                                                                                          ) || exit 666
 fi
 
  $(brew --prefix)/opt/llvm@19/bin/clang-format --dry-run -Werror include/**/*.hpp test/*.cpp
