updates for new computer, clang 21, gcc 15, cmake 4

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -1,6 +1,6 @@
 #!/bin/bash
 # sudo dpkg --add-architecture i386
-sudo apt install git cmake ninja-build ccache g++ clang binutils-gold libboost-dev make --no-install-recommends
+sudo apt install git cmake ninja-build ccache g++ clang binutils-gold libboost-dev make libclang-rt-dev libc++-dev nvidia-cuda-toolkit libfftw3-dev valgrind clang-tidy --no-install-recommends
 # sudo apt install lld ccache clang clang-tidy cmake cppcheck g++ git iwyu lcov libblas-dev pkg-config libfftw3-dev libboost-test-dev libboost-timer-dev libopenblas-dev libtbb-dev make ninja-build valgrind libboost-test-dev:i386 libboost-timer-dev:i386
 # sudo dnf install boost-devel blas-devel ccache clang clang-tools-extra cmake cppcheck fftw-devel git lcov libasan liblas-devel libubsan ninja-build valgrind
 # install circle # mkdir -p $HOME/bin && wget https://www.circle-lang.org/linux/build_latest.tgz -P $HOME/tmp/ && tar zxvf $HOME/tmp/build_latest.tgz --directory $HOME/bin/ && $HOME/bin/circle --version
@@ -49,28 +49,28 @@ export UBSAN_OPTIONS=print_stacktrace=1
  ([ -d .build.g++ ]            || CXX=g++                           cmake -S . -B .build.g++            -DCMAKE_BUILD_TYPE=Debug                                                               && cmake --build .build.g++            $CMT && (ctest --test-dir .build.g++   --rerun-failed $CTR || ctest --test-dir .build.g++            --rerun-failed $CTR) ) || exit 666
  ([ -d .build.clang++-rel ]    || CXX=clang++                       cmake -S . -B .build.clang++-rel    -DCMAKE_BUILD_TYPE=Release -DENABLE_TBLIS=ON -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=gold -Wl,--detect-odr-violations" && cmake --build .build.clang++-rel    $CMT && (ctest --test-dir .build.clang++-rel          $CTR || ctest --test-dir .build.clang++-rel    --rerun-failed $CTR) ) || exit 666
 #([ -d .build.clang++-16 ]     || CXX=clang++-16                    cmake -S . -B .build.clang++-16     -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20                                     && cmake --build .build.clang++-16     $CMT && (ctest --test-dir .build.clang++-16           $CTR || ctest --test-dir .build.clang++-16     --rerun-failed $CTR) ) || exit 666
- ([ -d .build.clang++ ]        || CXX=clang++ CXXFLAGS=-Weverything cmake -S . -B .build.clang++        -DCMAKE_BUILD_TYPE=Debug                                                               && cmake --build .build.clang++        $CMT && (ctest --test-dir .build.clang++              $CTR || ctest --test-dir .build.clang++        --rerun-failed $CTR) ) || exit 666
+ ([ -d .build.clang++ ]        || CXX=clang++ CXXFLAGS=-Weverything cmake -S . -B .build.clang++        -DCMAKE_BUILD_TYPE=Debug -DCMAKE_COMPILE_WARNING_AS_ERROR="ON"                                                               && cmake --build .build.clang++        $CMT && (ctest --test-dir .build.clang++              $CTR || ctest --test-dir .build.clang++        --rerun-failed $CTR) ) || exit 666
  ([ -d .build.clang++.c++23 ]  || CXX=clang++                       cmake -S . -B .build.clang++.c++23  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23                                     && cmake --build .build.clang++.c++23  $CMT && (ctest --test-dir .build.clang++.c++23        $CTR || ctest --test-dir .build.clang++.c++23  --rerun-failed $CTR) ) || exit 666
  ([ -d .build.g++.c++23 ]      || CXX=g++                           cmake -S . -B .build.g++.c++23      -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=23                                     && cmake --build .build.g++.c++23      $CMT && (ctest --test-dir .build.g++.c++23            $CTR || ctest --test-dir .build.g++.c++23      --rerun-failed $CTR) ) || exit 666
- ([ -d .build.clang++.libcpp ] || CXX=clang++                       cmake -S . -B .build.clang++.libcpp -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=23 -DDISABLE_MPI=1 -DCMAKE_CXX_FLAGS="-stdlib=libc++ -D_LIBCPP_DEBUG=1 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG -fsanitize=address,undefined"  && cmake --build .build.clang++.libcpp $CMT && (ctest --test-dir .build.clang++.libcpp $CTR || ctest --test-dir .build.clang++.libcpp --rerun-failed $CTR) ) || exit 666
- ([ -d .build.g++-rel ]        || CXX=g++                           cmake -S . -B .build.g++-rel        -DCMAKE_BUILD_TYPE=Release -DENABLE_TBLIS=ON -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE -DCMAKE_CXX_FLAGS="-Wodr -Wlto-type-mismatch" -DCMAKE_EXE_LINKER_FLAGS="-Wodr -Wlto-type-mismatch" && cmake --build .build.g++-rel        $CMT && (ctest --test-dir .build.g++-rel              $CTR || ctest --test-dir .build.g++-rel        --rerun-failed $CTR) ) || exit 666
+ ([ -d .build.clang++.libcpp ] || CXX=clang++                       cmake -S . -B .build.clang++.libcpp -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=23 -DDISABLE_MPI=1 -DCMAKE_CXX_FLAGS="-stdlib=libc++ -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG -fsanitize=address,undefined" -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++ -fsanitize=address,undefined"  && cmake --build .build.clang++.libcpp $CMT && (ctest --test-dir .build.clang++.libcpp $CTR || ctest --test-dir .build.clang++.libcpp --rerun-failed $CTR) ) || exit 666
+ ([ -d .build.g++-rel ]        || CXX=g++                           cmake -S . -B .build.g++-rel        -DCMAKE_BUILD_TYPE=Release -DENABLE_TBLIS=ON -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE -DCMAKE_CXX_FLAGS="-Wodr -Wlto-type-mismatch" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=gold -Wl,--detect-odr-violations -Wodr -Wlto-type-mismatch" && cmake --build .build.g++-rel        $CMT && (ctest --test-dir .build.g++-rel              $CTR || ctest --test-dir .build.g++-rel        --rerun-failed $CTR) ) || exit 666
 
 if [[ $(uname -m) != 'aarch64' ]]; then
- clang-format-20 --output-replacements-xml --dry-run -Werror include/**/*.hpp test/*.cpp || exit 666
+ clang-format --output-replacements-xml --dry-run -Werror include/**/*.hpp test/*.cpp || exit 666
 #diff -u include/**/*.hpp test/*.cpp <(clang-format-19 include/**/*.hpp test/*.cpp)
 
 #(CXX="$HOME/bin/circle" cmake -S . -B .build.circle     -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DDISABLE_MPI=1 -DCMAKE_CXX_EXTENSIONS=OFF -DENABLE_CIRCLE=1 -DCMAKE_THREAD_LIBS_INIT="-lpthread"                                                                                              && cmake --build .build.circle     $CMT && (ctest --test-dir .build.circle     $CTR || ctest --test-dir .build.circle     --rerun-failed $CTR)) || exit 666
- nice -n 15 bash -c '(DIR=.build.nvcc.debug-cu17; [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=17 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--extended-lambda --threads 2"                          -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=61     && cmake --build .build.nvcc.debug-cu17 $CMT && (ctest --test-dir .build.nvcc.debug-cu17 $CTR || ctest --test-dir .build.nvcc.debug-cu17 --rerun-failed $CTR))' || exit 666
- nice -n 15 bash -c '(DIR=.build.nvcc.debug;      [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--extended-lambda --threads 2"                          -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvcc.debug      $CMT && (ctest --test-dir .build.nvcc.debug $CTR      || ctest --test-dir .build.nvcc.debug      --rerun-failed $CTR))' || exit 666
- nice -n 15 bash -c '(DIR=.build.nvcc;            [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--extended-lambda --threads 2"                          -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvcc            $CMT && (ctest --test-dir .build.nvcc       $CTR      || ctest --test-dir .build.nvcc            --rerun-failed $CTR))' || exit 666
+ nice -n 15 bash -c '(DIR=.build.nvcc.debug-cu17; [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=17 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--extended-lambda --threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++-13 -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvcc.debug-cu17 $CMT && (ctest --test-dir .build.nvcc.debug-cu17 $CTR || ctest --test-dir .build.nvcc.debug-cu17 --rerun-failed $CTR))' || exit 666
+ nice -n 15 bash -c '(DIR=.build.nvcc.debug;      [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--extended-lambda --threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++-13 -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvcc.debug      $CMT && (ctest --test-dir .build.nvcc.debug $CTR      || ctest --test-dir .build.nvcc.debug      --rerun-failed $CTR))' || exit 666
+ nice -n 15 bash -c '(DIR=.build.nvcc;            [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--extended-lambda --threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++-13 -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvcc            $CMT && (ctest --test-dir .build.nvcc       $CTR      || ctest --test-dir .build.nvcc            --rerun-failed $CTR))' || exit 666
 #(source /opt/intel/oneapi/setvars.sh && CXX=/opt/intel/oneapi/compiler/latest/bin/icpx cmake -S . -B .build.icpx  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20                                                                                                                                      && cmake --build .build.icpx       $CMT && (ctest --test-dir .build.icpx       $CTR || ctest --test-dir .build.icpx       --rerun-failed $CTR)) || exit 666
 #(CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/compilers/bin/nvc++ cmake -S . -B .build.nvc++   -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DBLA_PREFER_PKGCONFIG=ON -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/compilers/bin/nvc++                                                   && cmake --build .build.nvc++      $CMT && (ctest --test-dir .build.nvc++      $CTR || ctest --test-dir .build.nvc++      --rerun-failed $CTR)) || exit 666
  nice -n 15 bash -c '([ -d .build.nvc++26 ] || CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/2026/compilers/bin/nvc++ cmake -S . -B .build.nvc++26 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DBLA_PREFER_PKGCONFIG=ON -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2026/compilers/bin/nvc++                                                   && cmake --build .build.nvc++26    $CMT && (ctest --test-dir .build.nvc++26    $CTR || ctest --test-dir .build.nvc++26    --rerun-failed $CTR))' || exit 666
- nice -n 15 bash -c '([ -d .build.culang ] || cmake -S . -B .build.culang       -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=clang++-19 -DCMAKE_CUDA_HOST_COMPILER=clang++-19 -DCMAKE_CXX_COMPILER=clang++-19                                                                                               && cmake --build .build.culang     $CMT && (ctest --test-dir .build.culang     $CTR || ctest --test-dir .build.culang     --rerun-failed $CTR))' || exit 666
+ nice -n 15 bash -c '([ -d .build.culang ] || cmake -S . -B .build.culang       -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=clang++-20 -DCMAKE_CUDA_HOST_COMPILER=clang++-20 -DCMAKE_CXX_COMPILER=clang++-20 -DCMAKE_CUDA_FLAGS="-Wno-unknown-cuda-version" -DCMAKE_CUDA_ARCHITECTURES=native                                                                                               && cmake --build .build.culang     $CMT && (ctest --test-dir .build.culang     $CTR || ctest --test-dir .build.culang     --rerun-failed $CTR))' || exit 666
 fi
 
- nice -n 15 bash -c '([ -d .build.g++.plus ] || CXX=g++     cmake -S . -B .build.g++.plus     -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23 -DDISABLE_MPI=1 -DBLA_VENDOR=OpenBLAS `#-DCMAKE_CXX_CPPCHECK="cppcheck;--enable=all;--suppress=missingIncludeSystem;--suppress=unhandledChar;--inline-suppr;--std=c++17;--checkers-report=cppcheck.report;--error-exitcode=1"` -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG=1" -DCMAKE_CXX_FLAGS="-DRUNNING_ON_VALGRIND -fconcepts-diagnostics-depth=4 -fimplicit-constexpr -Wlto-type-mismatch -Wodr -fanalyzer -Wno-analyzer-null-dereference -Wno-analyzer-possible-null-dereference -Wno-analyzer-malloc-leak -Wno-analyzer-use-of-uninitialized-value -Wno-analyzer-use-after-free" && cmake --build .build.g++.plus     $CMT && (PMIX_MCA_gds=hash ctest --test-dir .build.g++.plus      --rerun-failed --overwrite MemoryCheckCommandOptions=" --trace-children=yes --leak-check=full --track-origins=yes --show-leak-kinds=all --gen-suppressions=all --error-exitcode=1" --overwrite MemoryCheckSuppressionFile=$PWD/.valgrind-suppressions -T memcheck $CTR))' || exit 666
- ([ -d .build.clang++.plus ] || CXX=clang++ cmake -S . -B .build.clang++.plus -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DBLA_VENDOR=Generic -DCMAKE_CXX_CLANG_TIDY="clang-tidy" -DCMAKE_CXX_FLAGS="-g -fsanitize=undefined -fno-sanitize-recover=undefined -DUBSAN=1" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=undefined" `#-DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="iwyu;-Xiwyu;--mapping_file=/home/correaa/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls"`                                                                                                                                                                                                                         && cmake --build .build.clang++.plus $CMT && (                  ctest --test-dir .build.clang++.plus                                                                                                                                                                                                                                                                                        $CTR  || ctest --parallel 1 -rerun-failed $CTR)) || exit 666
+ nice -n 15 bash -c '([ -d .build.g++.plus ] || CXX=g++     cmake -S . -B .build.g++.plus     -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23 -DDISABLE_MPI=1 -DBLA_VENDOR=OpenBLAS `#-DCMAKE_CXX_CPPCHECK="cppcheck;--enable=all;--suppress=missingIncludeSystem;--suppress=unhandledChar;--inline-suppr;--std=c++17;--checkers-report=cppcheck.report;--error-exitcode=1"` -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG=1 -DRUNNING_ON_VALGRIND -fconcepts-diagnostics-depth=4 -fimplicit-constexpr -Wlto-type-mismatch -Wodr -Wno-analyzer-null-dereference -Wno-analyzer-possible-null-dereference -Wno-analyzer-malloc-leak -Wno-analyzer-use-of-uninitialized-value -Wno-analyzer-use-after-free" && cmake --build .build.g++.plus     $CMT && (PMIX_MCA_gds=hash ctest --test-dir .build.g++.plus      --rerun-failed --overwrite MemoryCheckCommandOptions="--trace-children=yes --leak-check=full --track-origins=yes --show-leak-kinds=all --gen-suppressions=all --error-exitcode=1" --overwrite MemoryCheckSuppressionFile=$PWD/.valgrind-suppressions -T memcheck $CTR))' || exit 666
+ ([ -d .build.clang++.plus ] || CXX=clang++ cmake -S . -B .build.clang++.plus -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DBLA_VENDOR=Generic -DCMAKE_CXX_CLANG_TIDY="clang-tidy" -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-sanitize-recover=undefined -fno-omit-frame-pointer -DUBSAN=1" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,undefined" `#-DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="iwyu;-Xiwyu;--mapping_file=/home/correaa/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls"`                                                                                                                                                                                                                         && cmake --build .build.clang++.plus $CMT && (                  ctest --test-dir .build.clang++.plus                                                                                                                                                                                                                                                                                        $CTR  || ctest --parallel 1 --rerun-failed $CTR)) || exit 666
 
 ## sudo setfacl --modify user:correaa:rw /var/run/docker.sock
 # gitlab-runner exec docker rocm
