rename extents

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -50,7 +50,7 @@ if [[ $OSTYPE != "darwin"* ]]; then
 export PMIX_MCA_gds=hash
 export UBSAN_OPTIONS=print_stacktrace=1
 
- ([ -d .build.g++ ]            || CXX=g++                           cmake -S . -B .build.g++            -DCMAKE_BUILD_TYPE=Debug -DCMAKE_COMPILE_WARNING_AS_ERROR=ON                                                           && cmake --build .build.g++            $CMT && (ctest --test-dir .build.g++   --rerun-failed $CTR || ctest --test-dir .build.g++            --rerun-failed $CTR) ) || exit 666
+ ([ -d .build.g++ ]            || CXX=g++                           cmake -S . -B .build.g++            -DCMAKE_BUILD_TYPE=Debug -DCMAKE_COMPILE_WARNING_AS_ERROR=ON   -DCMAKE_CXX_FLAGS="-Wno-error=deprecated-declarations"            && cmake --build .build.g++            $CMT && (ctest --test-dir .build.g++   --rerun-failed $CTR || ctest --test-dir .build.g++            --rerun-failed $CTR) ) || exit 666
 #([ -d .build.clang++ ]        || CXX=clang++ CXXFLAGS=-Weverything cmake -S . -B .build.clang++        -DCMAKE_BUILD_TYPE=Debug -DCMAKE_COMPILE_WARNING_AS_ERROR="ON"                                                               && cmake --build .build.clang++        $CMT && (ctest --test-dir .build.clang++              $CTR || ctest --test-dir .build.clang++        --rerun-failed $CTR) ) || exit 666
  ([ -d .build.clang++.libcpp ] || CXX=clang++                       cmake -S . -B .build.clang++.libcpp -DCMAKE_BUILD_TYPE=Debug -DCMAKE_COMPILE_WARNING_AS_ERROR=ON   -DCMAKE_CXX_STANDARD=23 -DDISABLE_MPI=1 -DCMAKE_CXX_FLAGS="-stdlib=libc++ -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG -fsanitize=address,undefined" -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++ -fsanitize=address,undefined"  && cmake --build .build.clang++.libcpp $CMT && (ctest --test-dir .build.clang++.libcpp $CTR || ctest --test-dir .build.clang++.libcpp --rerun-failed $CTR) ) || exit 666
 
