move pp c16 to end

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -48,18 +48,18 @@ export UBSAN_OPTIONS=print_stacktrack=1
 if [[ $(uname -m) != 'aarch64' ]]; then
  clang-format-19 --dry-run -Werror include/**/*.hpp test/*.cpp
 
- (CXX=clang++-16         cmake -S . -B .build.clang++-16  -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=20                                                         && cmake --build .build.clang++-16    $CMT && (ctest --test-dir .build.clang++-16    --parallel 8 $CTR || ctest --test-dir .build.clang++-16    --rerun-failed --output-on-failure $CTR) ) || exit 666
-#(CXX="$HOME/bin/circle" cmake -S . -B .build.circle     -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DDISABLE_MPI=1 -DCMAKE_CXX_EXTENSIONS=OFF -DENABLE_CIRCLE=1 -DCMAKE_THREAD_LIBS_INIT="-lpthread"                                                                                          && cmake --build .build.circle     $CMT && (ctest --test-dir .build.circle --parallel 8 $CTR || ctest --test-dir .build.circle --rerun-failed --output-on-failure $CTR)) || exit 666
- (                       cmake -S . -B .build.nvcc.relax -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr --threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURE=native && cmake --build .build.nvcc.relax $CMT && (ctest --test-dir .build.nvcc.relax   `#--parallel 8` $CTR || ctest --test-dir .build.nvcc.relax   --rerun-failed --output-on-failure $CTR)) || exit 666
- (                       cmake -S . -B .build.nvcc       -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=native                          && cmake --build .build.nvcc       $CMT && (ctest --test-dir .build.nvcc   --parallel 8 $CTR || ctest --test-dir .build.nvcc   --rerun-failed --output-on-failure $CTR)) || exit 666
-#(source /opt/intel/oneapi/setvars.sh && CXX=/opt/intel/oneapi/compiler/latest/bin/icpx cmake -S . -B .build.icpx  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20                                                                                                                                && cmake --build .build.icpx       $CMT && (ctest --test-dir .build.icpx   --parallel 8 $CTR || ctest --test-dir .build.icpx   --rerun-failed --output-on-failure $CTR)) || exit 666
- (CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/compilers/bin/nvc++ cmake -S . -B .build.nvc++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DBLA_PREFER_PKGCONFIG=ON -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/compilers/bin/nvc++                                               && cmake --build .build.nvc++  $CMT && (ctest --test-dir .build.nvc++  --parallel 8 $CTR || ctest --test-dir .build.nvc++  --rerun-failed --output-on-failure $CTR)) || exit 666
- (                       cmake -S . -B .build.culang       -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=clang++-19 -DCMAKE_CUDA_HOST_COMPILER=clang++-19 -DCMAKE_CXX_COMPILER=clang++-19                                                                    && cmake --build .build.culang $CMT && (ctest --test-dir .build.culang --parallel 8 $CTR || ctest --test-dir .build.culang --rerun-failed --output-on-failure $CTR)) || exit 666
+#(CXX="$HOME/bin/circle" cmake -S . -B .build.circle     -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DDISABLE_MPI=1 -DCMAKE_CXX_EXTENSIONS=OFF -DENABLE_CIRCLE=1 -DCMAKE_THREAD_LIBS_INIT="-lpthread"                                                                                              && cmake --build .build.circle     $CMT && (ctest --test-dir .build.circle      --parallel 8 $CTR || ctest --test-dir .build.circle     --rerun-failed --output-on-failure $CTR)) || exit 666
+#(                       cmake -S . -B .build.nvcc.relax -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr --threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURE=native  && cmake --build .build.nvcc.relax $CMT && (ctest --test-dir .build.nvcc.relax  --parallel 8 $CTR || ctest --test-dir .build.nvcc.relax --rerun-failed --output-on-failure $CTR)) || exit 666
+ (                       cmake -S . -B .build.nvcc       -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--threads 2"                          -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvcc       $CMT && (ctest --test-dir .build.nvcc        --parallel 8 $CTR || ctest --test-dir .build.nvcc       --rerun-failed --output-on-failure $CTR)) || exit 666
+#(source /opt/intel/oneapi/setvars.sh && CXX=/opt/intel/oneapi/compiler/latest/bin/icpx cmake -S . -B .build.icpx  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20                                                                                                                                      && cmake --build .build.icpx       $CMT && (ctest --test-dir .build.icpx        --parallel 8 $CTR || ctest --test-dir .build.icpx       --rerun-failed --output-on-failure $CTR)) || exit 666
+ (CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/compilers/bin/nvc++ cmake -S . -B .build.nvc++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DBLA_PREFER_PKGCONFIG=ON -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/compilers/bin/nvc++                                                     && cmake --build .build.nvc++      $CMT && (ctest --test-dir .build.nvc++       --parallel 8 $CTR || ctest --test-dir .build.nvc++      --rerun-failed --output-on-failure $CTR)) || exit 666
+ (                       cmake -S . -B .build.culang       -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=clang++-19 -DCMAKE_CUDA_HOST_COMPILER=clang++-19 -DCMAKE_CXX_COMPILER=clang++-19                                                                                               && cmake --build .build.culang     $CMT && (ctest --test-dir .build.culang      --parallel 8 $CTR || ctest --test-dir .build.culang     --rerun-failed --output-on-failure $CTR)) || exit 666
 fi
 
  (CXX=g++     cmake -S . -B .build.g++.plus     -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23 -DDISABLE_MPI=1 -DBLA_VENDOR=OpenBLAS `#-DCMAKE_CXX_CPPCHECK="cppcheck;--enable=all;--suppress=missingIncludeSystem;--inline-suppr;--std=c++17;--checkers-report=cppcheck.report;--error-exitcode=1"` -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG=1" -DCMAKE_CXX_FLAGS="-DRUNNING_ON_VALGRIND -fconcepts-diagnostics-depth=4 -fimplicit-constexpr -Wlto-type-mismatch -Wodr -fanalyzer -Wno-analyzer-null-dereference -Wno-analyzer-possible-null-dereference -Wno-analyzer-malloc-leak -Wno-analyzer-use-of-uninitialized-value -Wno-analyzer-use-after-free" && cmake --build .build.g++.plus     $CMT && (PMIX_MCA_gds=hash ctest --test-dir .build.g++.plus     --rerun-failed --parallel 8 --output-on-failure --rerun-failed --overwrite MemoryCheckCommandOptions=" --trace-children=yes --leak-check=full --track-origins=yes --show-leak-kinds=all --gen-suppressions=all --error-exitcode=1" --overwrite MemoryCheckSuppressionFile=$PWD/.valgrind-suppressions -T memcheck $CTR)                                                              ) || exit 666
  (CXX=clang++ cmake -S . -B .build.clang++.plus -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DBLA_VENDOR=Generic -DCMAKE_CXX_CLANG_TIDY="clang-tidy" -DCMAKE_CXX_FLAGS="-g -fsanitize=undefined -fno-sanitize-recover=undefined -DUBSAN=1" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=undefined" `#-DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="iwyu;-Xiwyu;--mapping_file=/home/correaa/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls"`                                                                                                                                                                                                                         && cmake --build .build.clang++.plus $CMT && (                  ctest --test-dir .build.clang++.plus --rerun-failed --parallel 8                                                                                                                                                                                                                                                                                       $CTR  || ctest --parallel 1 -rerun-failed --output-on-failure $CTR)) || exit 666
 
+ (CXX=clang++-16         cmake -S . -B .build.clang++-16  -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=20                                                         && cmake --build .build.clang++-16    $CMT && (ctest --test-dir .build.clang++-16    --parallel 8 $CTR || ctest --test-dir .build.clang++-16    --rerun-failed --output-on-failure $CTR) ) || exit 666
 ## sudo setfacl --modify user:correaa:rw /var/run/docker.sock
 # gitlab-runner exec docker rocm
 
