for each

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -24,8 +24,9 @@ export CMAKE_GENERATOR=Ninja
 
 export CMAKE_CUDA_COMPILER_LAUNCHER="ccache"
 export CMAKE_CXX_COMPILER_LAUNCHER="ccache"
+export CMAKE_C_COMPILER_LAUNCHER="ccache"
 export CMAKE_COMPILE_WARNING_AS_ERROR="ON"
-export CMAKE_BUILD_PARALLEL_LEVEL=8
+export CMAKE_BUILD_PARALLEL_LEVEL=$(($(nproc) - 2))
 export CTEST_PARALLEL_LEVEL=8
 export CTEST_OUTPUT_ON_FAILURE=1
 
@@ -55,8 +56,8 @@ if [[ $(uname -m) != 'aarch64' ]]; then
 #diff -u include/**/*.hpp test/*.cpp <(clang-format-19 include/**/*.hpp test/*.cpp)
 
 #(CXX="$HOME/bin/circle" cmake -S . -B .build.circle     -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DDISABLE_MPI=1 -DCMAKE_CXX_EXTENSIONS=OFF -DENABLE_CIRCLE=1 -DCMAKE_THREAD_LIBS_INIT="-lpthread"                                                                                              && cmake --build .build.circle     $CMT && (ctest --test-dir .build.circle     $CTR || ctest --test-dir .build.circle     --rerun-failed $CTR)) || exit 666
- (                       DIR=.build.nvcc.debug; [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--extended-lambda --threads 2"                          -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvcc.debug $CMT && (ctest --test-dir .build.nvcc.debug $CTR || ctest --test-dir .build.nvcc.debug --rerun-failed $CTR)) || exit 666
- (                       DIR=.build.nvcc      ; [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--extended-lambda --threads 2"                          -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvcc       $CMT && (ctest --test-dir .build.nvcc       $CTR || ctest --test-dir .build.nvcc       --rerun-failed $CTR)) || exit 666
+ (                       DIR=.build.nvcc.debug; [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="-v --extended-lambda --threads 2"                          -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvcc.debug $CMT && (ctest --test-dir .build.nvcc.debug $CTR || ctest --test-dir .build.nvcc.debug --rerun-failed $CTR)) || exit 666
+ (                       DIR=.build.nvcc      ; [ -d "$DIR" ] || cmake -S . -B "$DIR" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="-v --extended-lambda --threads 2"                          -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=native && cmake --build .build.nvcc       $CMT && (ctest --test-dir .build.nvcc       $CTR || ctest --test-dir .build.nvcc       --rerun-failed $CTR)) || exit 666
 #(source /opt/intel/oneapi/setvars.sh && CXX=/opt/intel/oneapi/compiler/latest/bin/icpx cmake -S . -B .build.icpx  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20                                                                                                                                      && cmake --build .build.icpx       $CMT && (ctest --test-dir .build.icpx       $CTR || ctest --test-dir .build.icpx       --rerun-failed $CTR)) || exit 666
 #(CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/compilers/bin/nvc++ cmake -S . -B .build.nvc++   -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DBLA_PREFER_PKGCONFIG=ON -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/compilers/bin/nvc++                                                   && cmake --build .build.nvc++      $CMT && (ctest --test-dir .build.nvc++      $CTR || ctest --test-dir .build.nvc++      --rerun-failed $CTR)) || exit 666
  ([ -d .build.nvc++26 ] || CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/2026/compilers/bin/nvc++ cmake -S . -B .build.nvc++26 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DBLA_PREFER_PKGCONFIG=ON -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2026/compilers/bin/nvc++                                                   && cmake --build .build.nvc++26    $CMT && (ctest --test-dir .build.nvc++26    $CTR || ctest --test-dir .build.nvc++26    --rerun-failed $CTR)) || exit 666
@@ -81,7 +82,7 @@ export CMAKE_PREFIX_PATH=$HOME/lib/cmake/thrust
  (CXX=c++ CXXFLAGS="-fexperimental-library" DIR=.build.c++.std23 cmake -S . -B .build.c++.std23 -DCMAKE_BUILD_TYPE=Debug   `#-DOpenMP_ROOT=/opt/homebrew/opt/libomp` -DENABLE_TBLIS=ON -DCMAKE_CXX_STANDARD=23                                                                                                                                                                                                       && cmake --build .build.c++.std23 $CMT &&                                           (ctest --test-dir .build.c++.std23 $CTR                      || ctest --verbose --test-dir .build.c++.std23 --rerun-failed $CTR) ) || exit 666
  (CXX=c++                                    cmake -S . -B .build.c++.asan  -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DENABLE_TBLIS=ON -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_FLAGS="-D_LIBCPP_DEBUG=1 -fsanitize=undefined -fsanitize=pointer-overflow -fsanitize-trap=pointer-overflow -fsanitize=address -fno-omit-frame-pointer -fsanitize=signed-integer-overflow" && cmake --build .build.c++.asan  $CMT && ASAN_OPTIONS="new_delete_type_mismatch=1"  ctest --test-dir .build.c++.asan  $CTR                                                                                          ) || exit 666
  (CXX=g++-15                                 cmake -S . -B .build.g++-15    -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    -DCMAKE_CXX_STANDARD=23 -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE -DCMAKE_CXX_FLAGS="-D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG=1 -D_FORTIFY_SOURCE=3"                                                                            && cmake --build .build.g++-15    $CMT &&                                            ctest --test-dir .build.g++-15    $CTR                                                                                          ) || exit 666
- (CXX=c++                                    cmake -S . -B .build.c++.plus  -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    `#-DCMAKE_CXX_CLANG_TIDY=clang-tidy` -DCMAKE_CXX_CPPLINT="cpplint;--quiet" -DCMAKE_CXX_FLAGS="-DCPPCHECK=1" -DCMAKE_CXX_CPPCHECK="cppcheck;-DCPPCHECK=1;--enable=all;--suppress=preprocessorErrorDirective;--suppress=missingIncludeSystem;--suppress=unhandledChar;--checkers-report=cppcheck.report;--suppress=checkersReport;--suppress=syntaxError;--suppress=unmatchedSuppression;--suppress=unusedFunction;--suppress=constParameterReference;--suppress=normalCheckLevelMaxBranches;--inline-suppr;--std=c++17;--error-exitcode=1" -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;--mapping_file=/Users/correatedesco1/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls;-Xiwyu;-Werror" && cmake --build .build.c++.plus $CMT --verbose --parallel && (ctest --test-dir .build.c++.plus -j 12 $CTR || ctest --test-dir .build.c++.tidy --rerun-failed $CTR)) || exit 666
+ (CXX=c++                                    cmake -S . -B .build.c++.plus  -DCMAKE_BUILD_TYPE=Release -DOpenMP_ROOT=/opt/homebrew/opt/libomp    `#-DCMAKE_CXX_CLANG_TIDY=clang-tidy` -DCMAKE_CXX_CPPLINT="cpplint;--quiet" -DCMAKE_CXX_FLAGS="-DCPPCHECK=1" -DCMAKE_CXX_CPPCHECK="cppcheck;-DCPPCHECK=1;--enable=all;--suppress=preprocessorErrorDirective;--suppress=missingIncludeSystem;--suppress=unhandledChar;--checkers-report=cppcheck.report;--suppress=checkersReport;--suppress=syntaxError;--suppress=unmatchedSuppression;--suppress=unusedFunction;--suppress=constParameterReference;--suppress=normalCheckLevelMaxBranches;--inline-suppr;--std=c++17;--error-exitcode=1" -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;--mapping_file=/Users/correatedesco1/boost-multi/.iwyu-test.imp;-Xiwyu;--no_fwd_decls;-Xiwyu;-Werror" && cmake --build .build.c++.plus $CMT --verbose --parallel && (ctest --test-dir .build.c++.plus $CTR || ctest --test-dir .build.c++.tidy --rerun-failed $CTR)) || exit 666
  (CXX=/opt/homebrew/opt/llvm@21/bin/clang++  cmake -S . -B .build.c++.std26 -DCMAKE_BUILD_TYPE=Release                                                                                                                        -DCMAKE_CXX_STANDARD=26                                                                                                                                                                                                       && cmake --build .build.c++.std26 $CMT &&                                           (ctest --test-dir .build.c++.std26 $CTR                      || ctest --verbose --test-dir .build.c++.std26 --rerun-failed $CTR) ) || exit 666
 
 if [[ $(uname -m) == 'arm64' ]]; then
