more general prepush

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -8,7 +8,7 @@
 #     curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
 #     echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list
 #     sudo apt-get update -y
-#     sudo apt-get install -y nvhpc-24-7
+#     sudo apt-get install -y nvhpc
 #   on Fedora:
 #   sudo yum-config-manager --add-repo https://developer.download.nvidia.com/hpc-sdk/rhel/nvhpc.repo && sudo yum install -y nvhpc-cuda-multi-24.5
 # install oneAPI
@@ -47,11 +47,11 @@ export UBSAN_OPTIONS=print_stacktrack=1
 if [[ $(uname -m) != 'aarch64' ]]; then
  clang-format-19 --dry-run -Werror include/**/*.hpp test/*.cpp
 
- (CXX="$HOME/bin/circle" cmake -S . -B .build.circle     -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DDISABLE_MPI=1 -DCMAKE_CXX_EXTENSIONS=OFF -DENABLE_CIRCLE=1 -DCMAKE_THREAD_LIBS_INIT="-lpthread"                                                                                          && cmake --build .build.circle     $CMT && (ctest --test-dir .build.circle --parallel 8 $CTR || ctest --test-dir .build.circle --rerun-failed --output-on-failure $CTR)) || exit 666
- (                       cmake -S . -B .build.nvcc.relax -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr --threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=75 && cmake --build .build.nvcc.relax $CMT && (ctest --test-dir .build.nvcc.relax   `#--parallel 8` $CTR || ctest --test-dir .build.nvcc.relax   --rerun-failed --output-on-failure $CTR)) || exit 666
- (                       cmake -S . -B .build.nvcc       -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=75                          && cmake --build .build.nvcc       $CMT && (ctest --test-dir .build.nvcc   --parallel 8 $CTR || ctest --test-dir .build.nvcc   --rerun-failed --output-on-failure $CTR)) || exit 666
+#(CXX="$HOME/bin/circle" cmake -S . -B .build.circle     -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DDISABLE_MPI=1 -DCMAKE_CXX_EXTENSIONS=OFF -DENABLE_CIRCLE=1 -DCMAKE_THREAD_LIBS_INIT="-lpthread"                                                                                          && cmake --build .build.circle     $CMT && (ctest --test-dir .build.circle --parallel 8 $CTR || ctest --test-dir .build.circle --rerun-failed --output-on-failure $CTR)) || exit 666
+ (                       cmake -S . -B .build.nvcc.relax -DCMAKE_BUILD_TYPE=Debug   -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr --threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURE=native && cmake --build .build.nvcc.relax $CMT && (ctest --test-dir .build.nvcc.relax   `#--parallel 8` $CTR || ctest --test-dir .build.nvcc.relax   --rerun-failed --output-on-failure $CTR)) || exit 666
+ (                       cmake -S . -B .build.nvcc       -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=nvcc -DCMAKE_CUDA_FLAGS="--threads 2" -DCMAKE_CUDA_HOST_COMPILER=g++ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_ARCHITECTURES=native                          && cmake --build .build.nvcc       $CMT && (ctest --test-dir .build.nvcc   --parallel 8 $CTR || ctest --test-dir .build.nvcc   --rerun-failed --output-on-failure $CTR)) || exit 666
 #(source /opt/intel/oneapi/setvars.sh && CXX=/opt/intel/oneapi/compiler/latest/bin/icpx cmake -S . -B .build.icpx  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20                                                                                                                                && cmake --build .build.icpx       $CMT && (ctest --test-dir .build.icpx   --parallel 8 $CTR || ctest --test-dir .build.icpx   --rerun-failed --output-on-failure $CTR)) || exit 666
- (CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/2024/compilers/bin/nvc++ cmake -S . -B .build.nvc++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DBLA_PREFER_PKGCONFIG=ON -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2024/compilers/bin/nvc++                                               && cmake --build .build.nvc++  $CMT && (ctest --test-dir .build.nvc++  --parallel 8 $CTR || ctest --test-dir .build.nvc++  --rerun-failed --output-on-failure $CTR)) || exit 666
+ (CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/compilers/bin/nvc++ cmake -S . -B .build.nvc++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DBLA_PREFER_PKGCONFIG=ON -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/compilers/bin/nvc++                                               && cmake --build .build.nvc++  $CMT && (ctest --test-dir .build.nvc++  --parallel 8 $CTR || ctest --test-dir .build.nvc++  --rerun-failed --output-on-failure $CTR)) || exit 666
  (                       cmake -S . -B .build.culang       -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=clang++-19 -DCMAKE_CUDA_HOST_COMPILER=clang++-19 -DCMAKE_CXX_COMPILER=clang++-19                                                                    && cmake --build .build.culang $CMT && (ctest --test-dir .build.culang --parallel 8 $CTR || ctest --test-dir .build.culang --rerun-failed --output-on-failure $CTR)) || exit 666
 fi
 
