removed equal_to  version

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -60,6 +60,8 @@ if [[ $(uname -m) != 'aarch64' ]]; then
 #(source /opt/intel/oneapi/setvars.sh && CXX=/opt/intel/oneapi/compiler/latest/bin/icpx cmake -S . -B .build.icpx  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20                                                                                                                                      && cmake --build .build.icpx       $CMT && (ctest --test-dir .build.icpx       $CTR || ctest --test-dir .build.icpx       --rerun-failed --output-on-failure $CTR)) || exit 666
  (CXX=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/compilers/bin/nvc++ cmake -S . -B .build.nvc++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DBLA_PREFER_PKGCONFIG=ON -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/2025/compilers/bin/nvc++                                                     && cmake --build .build.nvc++      $CMT && (ctest --test-dir .build.nvc++      $CTR || ctest --test-dir .build.nvc++      --rerun-failed --output-on-failure $CTR)) || exit 666
  (                       cmake -S . -B .build.culang       -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=clang++-19 -DCMAKE_CUDA_HOST_COMPILER=clang++-19 -DCMAKE_CXX_COMPILER=clang++-19                                                                                               && cmake --build .build.culang     $CMT && (ctest --test-dir .build.culang     $CTR || ctest --test-dir .build.culang     --rerun-failed --output-on-failure $CTR)) || exit 666
+#(                       cmake -S . -B .build.culang20     -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=clang++-20 -DCMAKE_CUDA_HOST_COMPILER=clang++-20 -DCMAKE_CXX_COMPILER=clang++-20          -DCMAKE_CUDA_ARCHITECTURES=native                                                                                     && cmake --build .build.culang20   $CMT && (ctest --test-dir .build.culang20   $CTR || ctest --test-dir .build.culang20   --rerun-failed --output-on-failure $CTR)) || exit 666
+ (                       cmake -S . -B .build.culang20     -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=1 -DCMAKE_CUDA_COMPILER=clang++-20 -DCMAKE_CUDA_HOST_COMPILER=clang++-19 -DCMAKE_CXX_COMPILER=clang++-20 -DCMAKE_CXX_STANDARD=20 -DCMAKE_CUDA_STANDARD=20   -DCMAKE_CUDA_ARCHITECTURES=61                                           && cmake --build .build.culang20   $CMT && (ctest --test-dir .build.culang20     $CTR || ctest --test-dir .build.culang20     --rerun-failed --output-on-failure $CTR)) || exit 666
 fi
 
  (CXX=g++     cmake -S . -B .build.g++.plus     -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23 -DDISABLE_MPI=1 -DBLA_VENDOR=OpenBLAS `#-DCMAKE_CXX_CPPCHECK="cppcheck;--enable=all;--suppress=missingIncludeSystem;--inline-suppr;--std=c++17;--checkers-report=cppcheck.report;--error-exitcode=1"` -DCMAKE_CXX_FLAGS="-D_GLIBCXX_DEBUG=1" -DCMAKE_CXX_FLAGS="-DRUNNING_ON_VALGRIND -fconcepts-diagnostics-depth=4 -fimplicit-constexpr -Wlto-type-mismatch -Wodr -fanalyzer -Wno-analyzer-null-dereference -Wno-analyzer-possible-null-dereference -Wno-analyzer-malloc-leak -Wno-analyzer-use-of-uninitialized-value -Wno-analyzer-use-after-free" && cmake --build .build.g++.plus     $CMT && (PMIX_MCA_gds=hash ctest --test-dir .build.g++.plus      --output-on-failure --rerun-failed --overwrite MemoryCheckCommandOptions=" --trace-children=yes --leak-check=full --track-origins=yes --show-leak-kinds=all --gen-suppressions=all --error-exitcode=1" --overwrite MemoryCheckSuppressionFile=$PWD/.valgrind-suppressions -T memcheck $CTR)                                                              ) || exit 666
